### ISSUE TITLE
Broken DPPN links

### ISSUE THREAD

**Issue by MaxxJohnson** [digitalpalireader/digitalpalireader#280] opened 2020-10-19 16:55 UTC
Green “n” DPPN links like the ones in picture aren’t working
![6F3B70B2-0BF8-4D26-8A62-5708931D3EEF](https://user-images.githubusercontent.com/60581658/96484229-44e89c00-120a-11eb-98f6-7d5e8833c90f.png)

**Comment by rrogowski** [comment] 2021-03-16 21:05
@parthopdas It looks like the DPPN links are working correctly when the bottom pane is already open, but clicking a DPPN does NOT open the bottom pane if it is closed.

https://user-images.githubusercontent.com/5777094/111379584-b0c81700-8679-11eb-8272-cdbbc828488e.mp4

Is the expected behavior that the bottom pane should open (if it is currently closed) when a DPPN link is clicked?

**Comment by parthopdas** [comment] 2021-03-16 21:31
@rrogowski yes the bottom pane should open if not already opened.

**Comment by rrogowski** [comment] 2021-03-21 01:13
@parthopdas It looks like I missed one scenario in my round of manual testing -- as a result of my change, I introduced a regression in the Search feature where the definition doesn't show up in the bottom pane:

https://user-images.githubusercontent.com/5777094/111890553-cbbfc180-89c0-11eb-96f4-dc63d6fe1011.mp4

I have a fix ready to go. Do you think it's worth it to revert https://github.com/digitalpalireader/digitalpalireader/pull/330 and resubmit the change, or should I just open a new PR with the fix?

**Comment by rrogowski** [comment] 2021-03-21 18:46
Closing as Max confirmed in the Discord channel that DPPN links are now working as expected!

**Closed by rrogowski** 2021-03-21 18:46 UTC
Labels: Effort: easy - 0.5 days, P2: would really help to ease a lot of friction
