### ISSUE TITLE
Search with regular expressions not working properly "\b"

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#214] opened 2020-05-10 10:55 UTC
\b at the beginning of a word works perfectly, but is not working at the end of a word. For example search **ttiṃ**\b which should give all the words ending in **ttiṃ**. 

![regex ttim](https://user-images.githubusercontent.com/64521731/81497046-8c711080-92d9-11ea-8107-726d612196a3.png)

But these are the results, the words contain **ttiṃ** but don't end in it. And there are way too few results! There should be hundreds ...

![regex ttiṃ results](https://user-images.githubusercontent.com/64521731/81497067-b32f4700-92d9-11ea-9eb3-7869693ee02d.png)

This behaviour is consistent with Palemoon.

**Comment by yuttadhammo** [comment] 2020-05-11 10:46
fixed in 93c47469e1a91dd0e50b669fcbbd3a67fb737453

may have caused regression though

**Closed by yuttadhammo** 2020-05-11 10:46 UTC

**Comment by bdhrs** [comment] 2020-05-11 14:13
Just checked in staging, now there are 0 results for the above search.

**Comment by yuttadhammo** [comment] 2020-05-11 18:17
That's not my fault, someone broke it again.

**Comment by yuttadhammo** [comment] 2020-05-11 18:21
It works for me if I actually type that into the search box, but for some reason refreshing the page shows 0 results. @parthopdas

**Comment by yuttadhammo** [comment] 2020-05-11 18:41
The problem is in the permalink creation. I've just switched it to use unicode. Seems to fix the problem.

**Comment by bdhrs** [comment] 2020-05-12 02:14
yes, that's working perfectly now. thanks!
